apiVersion: v1
kind: Secret
metadata:
  name: oauth2-proxy-secret
type: Opaque
stringData:
  # Replace these with actual values
  cookie-secret: replace-with-32-byte-random-string
  client-id: replace-with-oauth-client-id
  client-secret: replace-with-oauth-client-secret