apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../manifests/common/configmap.yaml
  - ../../manifests/ui/pvc.yaml
  - ../../manifests/ui/deployment.yaml
  - ../../manifests/ui/service.yaml
  - ../../manifests/agents/google_adk/deployment.yaml
  - ../../manifests/agents/google_adk/service.yaml
  - ../../manifests/agents/repo_cloner/deployment.yaml
  - ../../manifests/agents/repo_cloner/service.yaml